import assert from 'node:assert/strict';
import test from 'node:test';
import { AutonomousOperationalContinuationService } from '../services/autonomous-operational-continuation-service.js';
class Domain{constructor(){this.m=new Map();}key(t,i){return`${t}:${i}`;}list(t){return[...this.m.entries()].filter(([k])=>k.startsWith(`${t}:`)).map(([,v])=>structuredClone(v));}get(t,i){return this.m.get(this.key(t,i))||null;}async put(t,i,p){this.m.set(this.key(t,i),structuredClone(p));return p;}}
async function base(){const d=new Domain();await d.put('EXPORT_PACKAGE','EXP-6',{id:'EXP-6',exportPackageId:'EXP-6',exportKind:'FINANCING_DISBURSEMENT',financingTransactionId:'FTX-6',closingId:'FCL-6',disbursementId:'FDB-6',opportunityId:'OPP-6',borrowerParticipantId:'P-6'});await d.put('FUNDING_OPPORTUNITY','OPP-6',{id:'OPP-6',opportunityId:'OPP-6',financingStage:'READY_TO_FUND'});await d.put('FINANCING_CLOSING','FCL-6',{id:'FCL-6',closingId:'FCL-6',status:'AUTHORIZED',borrowerParticipantId:'P-6',settlementInstructions:{assetAccountId:'A-6'}});await d.put('FINANCING_DISBURSEMENT','FDB-6',{id:'FDB-6',disbursementId:'FDB-6',closingId:'FCL-6',status:'SUBMITTED'});return d;}
const outcomes=(status='VERIFIED')=>({async reconcile(){},summary(){return{phase:4,status,verified:status==='VERIFIED'};},latestOutcome(){return{evidence:[{externalReference:'EXT-6'}]};}});
const counterparty=(status='COUNTERPARTY_OPERATIONS_ACTIVE')=>({statusForPackage(){return{phase:5,status};}});
test('reserved Phase 5 authority stops autonomous continuation',async()=>{const d=await base(),s=new AutonomousOperationalContinuationService(d,{outcomes:outcomes(),counterparty:counterparty('AWAITING_AUTHORITY')});const e=await s.evaluate('EXP-6');assert.equal(e.autonomous,false);assert.equal(e.status,'AWAITING_PRINCIPAL_AUTHORITY');assert.equal(e.nextAction,'PRINCIPAL_REVIEW_REQUIRED');});
test('failed external outcome stops autonomous continuation',async()=>{const d=await base(),s=new AutonomousOperationalContinuationService(d,{outcomes:outcomes('FAILED_EXTERNAL_OUTCOME'),counterparty:counterparty()});const e=await s.evaluate('EXP-6');assert.equal(e.autonomous,false);assert.equal(e.nextAction,'RECONCILE_FAILED_EXTERNAL_OUTCOME');});
test('verified outside evidence permits recording settlement but does not authorize settlement',async()=>{const d=await base(),s=new AutonomousOperationalContinuationService(d,{outcomes:outcomes(),counterparty:counterparty()});const e=await s.evaluate('EXP-6');assert.equal(e.autonomous,true);assert.equal(e.nextAction,'RECORD_VERIFIED_SETTLEMENT');assert.equal(e.externalReference,'EXT-6');});
test('funded financing with missing servicing context creates follow-up instead of inventing fields',async()=>{const d=await base();await d.put('FINANCING_CLOSING','FCL-6',{id:'FCL-6',closingId:'FCL-6',status:'FUNDED',borrowerParticipantId:'P-6'});await d.put('FUNDING_OPPORTUNITY','OPP-6',{id:'OPP-6',opportunityId:'OPP-6',financingStage:'FUNDED'});const s=new AutonomousOperationalContinuationService(d,{outcomes:outcomes(),counterparty:counterparty()});const result=await s.execute('EXP-6');assert.equal(result.record.status,'FOLLOW_UP_REQUIRED');assert.equal(d.list('AUTONOMOUS_CONTINUATION_FOLLOW_UP').length,1);assert.deepEqual(result.record.missingFields,['assetAccountId']);});
test('terminal servicing state creates authoritative closure follow-up instead of directly mutating closing',async()=>{const d=await base();await d.put('FINANCING_CLOSING','FCL-6',{id:'FCL-6',closingId:'FCL-6',status:'SERVICING',servicingAccountId:'ASA-6',borrowerParticipantId:'P-6'});await d.put('FUNDING_OPPORTUNITY','OPP-6',{id:'OPP-6',opportunityId:'OPP-6',financingStage:'SERVICING'});await d.put('ASSET_SERVICING_ACCOUNT','ASA-6',{id:'ASA-6',servicingAccountId:'ASA-6',assetAccountId:'A-6',ownerId:'P-6',state:'COMPLETED'});const s=new AutonomousOperationalContinuationService(d,{outcomes:outcomes(),counterparty:counterparty()});const result=await s.execute('EXP-6');assert.equal(result.record.status,'FOLLOW_UP_REQUIRED');assert.equal(result.record.nextAction,'COMPLETE_FINANCING_CLOSURE');assert.equal(d.get('FUNDING_OPPORTUNITY','OPP-6').financingStage,'SERVICING');assert.equal(d.get('FINANCING_CLOSING','FCL-6').status,'SERVICING');assert.equal(d.list('AUTONOMOUS_CONTINUATION_FOLLOW_UP').length,1);});
