import assert from 'node:assert/strict';
import test from 'node:test';
import { CounterpartyOperationsService } from '../services/counterparty-operations-service.js';
class Domain{constructor(){this.m=new Map();}key(t,i){return `${t}:${i}`;}list(t){return [...this.m.entries()].filter(([k])=>k.startsWith(`${t}:`)).map(([,v])=>structuredClone(v));}async put(t,i,p){this.m.set(this.key(t,i),structuredClone(p));return p;}}
const reasoning={reasonForExportPackage(){return{unresolvedFields:[],unresolvedServicingFields:[]};}};
const outcomes={summary(){return{status:'EXTERNAL_ACTIVITY_RECORDED'};}};
async function seed(d,event){await d.put('EXPORT_PACKAGE','EXP-5',{id:'EXP-5',exportPackageId:'EXP-5',financingTransactionId:'FTX-5',exportKind:'FINANCING_DISBURSEMENT',state:'READY_FOR_SETTLEMENT_INSTRUCTION',amount:250000,currency:'USD',settlementMethod:'ACH'});await d.put('TRANSACTION_PARTICIPATION_EVENT',event.eventId,{id:event.eventId,windowId:'TPW-5',exportPackageId:'EXP-5',financingTransactionId:'FTX-5',...event,createdAt:new Date().toISOString()});}
test('answers ordinary processing clarification from recorded transaction context',async()=>{const d=new Domain();await seed(d,{eventId:'TPE-Q',eventType:'PROCESSING_CLARIFICATION_REQUESTED',summary:'Which ACH instructions should our processing team use?',details:{topic:'ACH'}});const s=new CounterpartyOperationsService(d,{reasoning,outcomes});const r=await s.resolveParticipationEvent('TPE-Q');assert.equal(r.status,'ANSWERED_FROM_TRANSACTION_RECORD');assert.equal(r.authorityRequired,false);assert.match(r.response,/EXP-5/);assert.match(r.response,/ACH/);assert.equal(d.list('COUNTERPARTY_OPERATION_CASE').length,1);});
test('routes requested financing changes to principal authority without changing terms',async()=>{const d=new Domain();await seed(d,{eventId:'TPE-C',eventType:'PROCESSING_CLARIFICATION_REQUESTED',summary:'Can you increase the financing amount before we process this?',details:{topic:'AMOUNT_CHANGE'}});const s=new CounterpartyOperationsService(d,{reasoning,outcomes});const r=await s.resolveParticipationEvent('TPE-C');assert.equal(r.status,'AWAITING_PRINCIPAL_AUTHORITY');assert.equal(r.authorityRequired,true);assert.equal(d.list('EXPORT_PACKAGE')[0].amount,250000);assert.equal(d.list('COUNTERPARTY_OPERATION_CASE')[0].status,'AWAITING_AUTHORITY');});
test('keeps processing exceptions governed and transaction-bound',async()=>{const d=new Domain();await seed(d,{eventId:'TPE-E',eventType:'PROCESSING_EXCEPTION_REPORTED',summary:'Our processor cannot match the package reference.',details:{topic:'PACKAGE_REFERENCE',blocking:true}});const s=new CounterpartyOperationsService(d,{reasoning,outcomes});const r=await s.resolveParticipationEvent('TPE-E');assert.equal(r.status,'EXCEPTION_UNDER_REVIEW');assert.equal(r.nextAction,'REASON_EXCEPTION_AND_CONTINUE');assert.equal(s.statusForPackage('EXP-5').status,'EXCEPTION_RESOLUTION_ACTIVE');});
test('is idempotent for the same counterparty event',async()=>{const d=new Domain();await seed(d,{eventId:'TPE-I',eventType:'PROCESSING_CLARIFICATION_REQUESTED',summary:'Please confirm the current package.',details:{topic:'GENERAL_PROCESSING'}});const s=new CounterpartyOperationsService(d,{reasoning,outcomes});const a=await s.resolveParticipationEvent('TPE-I');const b=await s.resolveParticipationEvent('TPE-I');assert.equal(a.responseId,b.responseId);assert.equal(d.list('COUNTERPARTY_OPERATION_RESPONSE').length,1);});
