import assert from 'node:assert/strict';
import test from 'node:test';
import { ExternalTransferExecutionService } from '../services/external-transfer-execution-service.js';
class D{constructor(){this.m=new Map();this.fail=false;}k(t,i){return `${t}:${i}`;}get(t,i){return structuredClone(this.m.get(this.k(t,i))||null);}list(t){return [...this.m.entries()].filter(([k])=>k.startsWith(`${t}:`)).map(([,v])=>structuredClone(v));}async put(t,i,p){this.m.set(this.k(t,i),structuredClone(p));}async atomicPut(c){if(this.fail)throw new Error('atomic failure');for(const x of c)this.m.set(this.k(x.type,x.id),structuredClone(x.payload));}}
async function seed(d){
 await d.put('SRA_TRANSACTION','XFR-1',{transactionId:'XFR-1',transferInstructionId:'XFR-1',transactionType:'EXTERNAL_TRANSFER_INSTRUCTION',exportPackageId:'EXP-1',participantId:'P1',instrumentId:'INS-1',positionId:'CP-1',quantity:10,unit:'SRA',route:'CUSTODY',destinationReference:'DEST',state:'TRANSFER_INSTRUCTION_VERIFIED',executionState:'NOT_AUTHORIZED'});
 await d.put('EXPORT_PACKAGE','EXP-1',{exportPackageId:'EXP-1',ownershipRecognitionId:'OWN-1',participantId:'P1',instrumentId:'INS-1',positionId:'CP-1',quantity:10,state:'TRANSFER_INSTRUCTION_VERIFIED'});
 await d.put('COIN_POSITION','CP-1',{coinPositionId:'CP-1',participantId:'P1',instrumentId:'INS-1',availableQuantity:10,state:'ACTIVE'});
 await d.put('OWNERSHIP_RECOGNITION','OWN-1',{ownershipRecognitionId:'OWN-1',participantId:'P1',instrumentId:'INS-1',state:'RECOGNIZED'});
}
test('authorization does not move position and completed reconciliation does',async()=>{const d=new D();await seed(d);const s=new ExternalTransferExecutionService(d);await s.approve({action:'AUTHORIZE_EXECUTION',transferInstructionId:'XFR-1',approval:'APPROVE'},'A');assert.equal(d.get('COIN_POSITION','CP-1').availableQuantity,10);await s.approve({action:'RECONCILE_RESULT',transferInstructionId:'XFR-1',result:'COMPLETED',externalReference:'EXT-1',approval:'APPROVE'},'A');assert.equal(d.get('COIN_POSITION','CP-1').availableQuantity,0);assert.equal(d.get('OWNERSHIP_RECOGNITION','OWN-1').state,'EXTERNALLY_HELD');});
test('failed reconciliation preserves internal position',async()=>{const d=new D();await seed(d);const s=new ExternalTransferExecutionService(d);await s.approve({action:'AUTHORIZE_EXECUTION',transferInstructionId:'XFR-1',approval:'APPROVE'},'A');await s.approve({action:'RECONCILE_RESULT',transferInstructionId:'XFR-1',result:'FAILED',externalReference:'ERR-1',approval:'APPROVE'},'A');assert.equal(d.get('COIN_POSITION','CP-1').availableQuantity,10);assert.equal(d.get('OWNERSHIP_RECOGNITION','OWN-1').state,'RECOGNIZED');});
test('atomic failure leaves lifecycle unchanged',async()=>{const d=new D();await seed(d);d.fail=true;const s=new ExternalTransferExecutionService(d);await assert.rejects(()=>s.approve({action:'AUTHORIZE_EXECUTION',transferInstructionId:'XFR-1',approval:'APPROVE'},'A'),/atomic failure/);assert.equal(d.get('SRA_TRANSACTION','XFR-1').executionState,'NOT_AUTHORIZED');});
