import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs';
import { CounterpartyOperationsService } from '../services/counterparty-operations-service.js';
import { TransactionParticipationGatewayService } from '../services/transaction-participation-gateway-service.js';
class Domain{constructor(){this.m=new Map();}key(t,i){return`${t}:${i}`;}list(t){return[...this.m.entries()].filter(([k])=>k.startsWith(`${t}:`)).map(([,v])=>structuredClone(v));}async put(t,i,p){this.m.set(this.key(t,i),structuredClone(p));return p;}}
const reasoning={reasonForExportPackage(){return{unresolvedFields:[],unresolvedServicingFields:[]};}};
async function seed(d,event){await d.put('EXPORT_PACKAGE','EXP-REVIEW',{id:'EXP-REVIEW',exportPackageId:'EXP-REVIEW',financingTransactionId:'FTX-REVIEW',exportKind:'FINANCING_DISBURSEMENT',state:'READY_FOR_SETTLEMENT_INSTRUCTION',amount:250000,currency:'USD',settlementMethod:'ACH'});await d.put('TRANSACTION_PARTICIPATION_EVENT',event.eventId,{id:event.eventId,windowId:'TPW-REVIEW',exportPackageId:'EXP-REVIEW',financingTransactionId:'FTX-REVIEW',...event,createdAt:new Date().toISOString()});}
test('recognizes protected authority intent with optional articles even when topic is GENERAL_PROCESSING',async()=>{const requests=['authorize the payment','authorize the settlement','approve the financing','transfer the ownership','issue an instrument','execute the transfer'];for(const[index,summary]of requests.entries()){const d=new Domain(),eventId=`TPE-P-${index}`;await seed(d,{eventId,eventType:'PROCESSING_CLARIFICATION_REQUESTED',summary,details:{topic:'GENERAL_PROCESSING'}});const outcomes={async reconcile(){},summary(){return{status:'EXTERNAL_ACTIVITY_RECORDED'};}};const result=await new CounterpartyOperationsService(d,{reasoning,outcomes}).resolveParticipationEvent(eventId);assert.equal(result.status,'AWAITING_PRINCIPAL_AUTHORITY',summary);assert.equal(result.nextAction,'PRINCIPAL_REVIEW_REQUIRED',summary);}});
test('reconciles before replaying a persisted response and refreshes changed grounding',async()=>{const d=new Domain();await seed(d,{eventId:'TPE-REPLAY',eventType:'PROCESSING_CLARIFICATION_REQUESTED',summary:'Can we continue?',details:{topic:'GENERAL_PROCESSING'}});let status='EXTERNAL_ACTIVITY_RECORDED';const outcomes={async reconcile(){},summary(){return{status};}};const service=new CounterpartyOperationsService(d,{reasoning,outcomes});const first=await service.resolveParticipationEvent('TPE-REPLAY');assert.equal(first.nextAction,'CONTINUE_CURRENT_RECORDED_PROCESS');status='FAILED_EXTERNAL_OUTCOME';const second=await service.resolveParticipationEvent('TPE-REPLAY');assert.equal(second.nextAction,'RECONCILE_FAILED_EXTERNAL_OUTCOME');assert.equal(second.groundedIn.outcomeStatus,'FAILED_EXTERNAL_OUTCOME');assert.equal(d.list('COUNTERPARTY_OPERATION_RESPONSE').length,1);});
test('current verified outcome clears historical failed block from status projection',async()=>{const d=new Domain();await seed(d,{eventId:'TPE-STATUS',eventType:'PROCESSING_CLARIFICATION_REQUESTED',summary:'Continue?',details:{topic:'GENERAL_PROCESSING'}});let status='FAILED_EXTERNAL_OUTCOME';const outcomes={async reconcile(){},summary(){return{status};}};const service=new CounterpartyOperationsService(d,{reasoning,outcomes});await service.resolveParticipationEvent('TPE-STATUS');assert.equal(service.statusForPackage('EXP-REVIEW').status,'FAILED_EXTERNAL_OUTCOME_BLOCKED');status='VERIFIED';await service.resolveParticipationEvent('TPE-STATUS');assert.notEqual(service.statusForPackage('EXP-REVIEW').status,'FAILED_EXTERNAL_OUTCOME_BLOCKED');assert.equal(service.statusForPackage('EXP-REVIEW').currentOutcomeStatus,'VERIFIED');});
test('idempotency key rejects a changed request',async()=>{const d=new Domain(),gateway=new TransactionParticipationGatewayService(d),window={windowId:'TPW-IDEMP',exportPackageId:'EXP-IDEMP',financingTransactionId:'FTX-IDEMP'};await gateway.recordEvent(window,'PROCESSING_CLARIFICATION_REQUESTED',{summary:'Question one',idempotencyKey:'REQ-123'});await assert.rejects(()=>gateway.recordEvent(window,'PROCESSING_CLARIFICATION_REQUESTED',{summary:'Question two',idempotencyKey:'REQ-123'}),/different participation request/i);assert.equal(d.list('TRANSACTION_PARTICIPATION_EVENT').length,1);});
test('replay restores a missing operational observation after partial failure',async()=>{const d=new Domain(),gateway=new TransactionParticipationGatewayService(d),window={windowId:'TPW-OBS',exportPackageId:'EXP-OBS',financingTransactionId:'FTX-OBS'};const originalObserve=gateway.observe.bind(gateway);let fail=true;gateway.observe=async(input)=>{if(fail){fail=false;throw new Error('observation unavailable');}return originalObserve(input);};await assert.rejects(()=>gateway.recordEvent(window,'PROCESSING_CLARIFICATION_REQUESTED',{summary:'Question',idempotencyKey:'REQ-OBS'}),/observation unavailable/);assert.equal(d.list('TRANSACTION_PARTICIPATION_EVENT').length,1);assert.equal(d.list('OPERATIONAL_EVENT').length,0);await gateway.recordEvent(window,'PROCESSING_CLARIFICATION_REQUESTED',{summary:'Question',idempotencyKey:'REQ-OBS'});assert.equal(d.list('OPERATIONAL_EVENT').length,1);});
test('document route checks replay before document storage',()=>{const source=fs.readFileSync(new URL('../routes/transaction-participation-gateway-router.js',import.meta.url),'utf8');const replay=source.indexOf('documentReplay');const store=source.indexOf('documents.store');assert.ok(replay>=0&&store>replay);assert.match(source,/status\(200\).*replayed:true/);});
test('HTTP routes accept stable idempotency keys and private admin exposes Phase 5 status',()=>{const participation=fs.readFileSync(new URL('../routes/transaction-participation-gateway-router.js',import.meta.url),'utf8');assert.match(participation,/idempotency-key/);assert.match(participation,/x-idempotency-key/);const admin=fs.readFileSync(new URL('../routes/agent-workforce-admin-routes.js',import.meta.url),'utf8');assert.match(admin,/\/api\/admin\/counterparty-operations/);assert.match(admin,/requireAdmin/);assert.match(admin,/CounterpartyOperationsStatusService/);});
